/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobuku_gui;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import service.KoneksiDB;

/**
 *
 * @author HP
 */
public class DataPenulisKategori extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection obj = new KoneksiDB().getConnection();
    /**
     * Creates new form DataPenulisKategori
     */
    public DataPenulisKategori() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void tampilDataPenulis(){
        model = new DefaultTableModel();
        
        model.addColumn("No.");
        model.addColumn("Nama");
        model.addColumn("Gender");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        
        try{
            Statement s = (Statement) obj.createStatement();
            ResultSet result = s.executeQuery(
                    "select * from penulis"
            );
            System.out.println(result.getStatement());
            Integer nomor = 1;
            while (result.next()) {
                Object [] ob = new Object[10];
                ob[0] = nomor++;
                ob[1] = result.getString("nama"); 
                ob[2] = result.getString("gender");
                ob[3] = result.getString("alamat");
                ob[4] = result.getString("no_telp");
                
                model.addRow(ob);
            }
            jTable1.setModel(model);
            s.close();
            this.setTitle("Data Penulis");
            jLabel3.setText("Data Penulis");
            
        } catch (SQLException e) {
            Logger.getLogger(TokoBuku.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void tampilDataKategori(){
        model = new DefaultTableModel();
        
        model.addColumn("No.");
        model.addColumn("Nama Kategori");
        model.addColumn("Kode Rak");
        
        try{
            Statement s = (Statement) obj.createStatement();
            ResultSet result = s.executeQuery(
                    "select * from kategori"
            );
            System.out.println(result.getStatement());
            Integer nomor = 1;
            while (result.next()) {
                Object [] ob = new Object[10];
                ob[0] = nomor++;
                ob[1] = result.getString("nama"); 
                ob[2] = result.getString("kode_rak");
                
                model.addRow(ob);
            }
            jTable1.setModel(model);
            s.close();
            this.setTitle("Data Kategori");
            jLabel3.setText("Data Kategori");
            
        } catch (SQLException e) {
            Logger.getLogger(TokoBuku.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Data Penulis");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPenulisKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPenulisKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPenulisKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPenulisKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPenulisKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
